name: Multi-Job-WorkFlow

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
  
  Test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Start Testing
      run: |
        echo "Test results" > testresults.txt 
        echo "Testing comepleted"
        ls -ltra

  Deploy-job:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Code in prod
      run: testresults.txt
