name: Multi-Job-WorkFlow

on: push

env:
  NAME: Sai Natha Reddy
  PASSWORD: NoPassword

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
  
  Test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
    - name: Start Testing
      run: |
        echo "Test results" > testresults.txt 
        echo "Testing comepleted"
        ls -ltra
        echo "Get variable from WorkFlow -  $NAME"
        echo "Get variable from WorkFlow -  $PASSWORD"
    - name: Upload to Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Test-results
        path: testresults.txt

  Deploy-job:
    needs: [build-job, Test-job ]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: Test-results
    - name: Deploy Code in prod
      run: cat testresults.txt
