name: My Fisrt App

on: push

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome Message
      run: echo "Welcome to GitHub Actions"
    
    - name: Checkout Code 
      uses: actions/checkout@v5

    - name: List files
      runs: ls